### ISSUE TITLE
Crash between cofhcore and hodgepodge at launch

### ISSUE THREAD

**Issue by quentin452** [GTNewHorizons/Hodgepodge#136]
This issue doesn't appaer when hodgepodge is disabled

mods list : 

hodgepodge-1.7.10-2.0.1
gtnhmixins-2.0.1
gtnhlib-1.7.10-0.0.6
CoFHCore-[1.7.10]3.1.4-329

logs : 

https://paste.ee/p/Sol73

**Comment by quentin452** [comment]
fixed by disabling 

fixEatingStackedStew,
fixDimensionChangeHearts,
fixHopperHitBox,
fixImmobileFireballs,
fixPotionIterating,
fixResizableFullscreen,
fixUnfocusedFullscreen,
fixWorldServerLeakingUnloadedEntities,
speedupAnimations,
enableTileRendererProfiler,
fixPotionEffectRender,
fixPotionRenderOffset,
hideCrosshairInThirdPerson,
transparentChat,
furnacesPollute,

in hodpodge 

and update hodgepodge,gtnhlib

**Comment by DarianLStephens** [comment]
Mixingasm didn't seem to help here.
This is the error I get:
https://pastebin.com/GLA6BELc

**Comment by glowredman** [comment]
@DarianLStephens FalseTweaks is incompatible with GTNH Mixins (https://github.com/GTNewHorizons/GTNHMixins/issues/1), which is required for Hodgepodge.

**Comment by DarianLStephens** [comment]
Oh dang, that sucks. There's a lot in Hodgepodge I'd really like to have.

**Comment by mitchej123** [comment]
COFH works in our full pack, but with limited mods something goes wrong with it.  I haven't had a chance to look into it.  Falsetweaks is incompatible unfortunately, not much I can do there.
