### ISSUE TITLE
Falsepattern's mixins libs not work

### ISSUE THREAD

**Issue by jrslwq** [GTNewHorizons/Hodgepodge#149]
pls fix this problem
crash log below:
[crash-2022-12-13_20.14.52-client.txt](https://github.com/GTNewHorizons/Hodgepodge/files/10219319/crash-2022-12-13_20.14.52-client.txt)

**Comment by mitchej123** [comment]
The lib is incompatible.

**Comment by Glease** [comment]
Set noNukeBaseMod to false in config/hodgepodgeEarly.properties, or do the equivalent to falsetweaks.

**Comment by jrslwq** [comment]
Set noNukeBaseMod to true if you want use both mods

**Comment by unilock** [comment]
The equivalent config setting in `falsetweaks.cfg` appears to be `B:STARTUP_OPTIMIZATIONS`. Set it to `false` if you'd rather use whatever Hodgepodge implements.
