### ISSUE TITLE
Crash on startup with hodgepodge: version #25 and above from jenkins

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/Hodgepodge#16]
Thanks for opening an issue page for this repo.

The problem seems to be happening only in build http://jenkins.usrv.eu:8080/job/Hodgepodge/25/ and above, the game refuses to even start compared to version 24, where it loads correctly. Just tested with #28 and it's doing the same thing.
Here's a fresh crash with version 28, the game outright refuses to start. https://paste.ee/p/vCRkH

Thanks in advance!

**Comment by mitchej123** [comment]
Try editing the config and setting `B:fixGuiGameOver=true` to false.

**Comment by tyrael93** [comment]
Oh god big :brain: moment. I didn't even notice there was a config where you could toggle the different patches to begin with, this even fixes up the several other startup "errors" related to IC2 and the pollution ASM.
Thanks, that fixed it.
