### ISSUE TITLE
speedupVanillaFurnace breaks Mekanism's Energized Smelter

### ISSUE THREAD

**Issue by AstroTibs** [GTNewHorizons/Hodgepodge#165]
I'm not sure if there's anything you can do about this, if not, it might be worth making a note somewhere.

With **speedupVanillaFurnace** set to `true`, Mekanism's _Energized Smelter_ no longer works. As in, it no longer cooks anything.

I tried on Hodgepodge v2.0.1 and 2.0.22-pre, with a handful of versions in between.
I also tried using the last 1.7.10 release of Mekanism, and various versions of Mekanism: Community Edition. This exact issue is present for each of them.

**Comment by mitchej123** [comment]
Please provide a full log booting your pack, as well as any attempts to smelt.  Additionally, running with these options might help identify the issue:
```
-Dmixin.debug=true # Enable Mixin Debug
-Dmixin.debug.verbose=true # Verbose Debug Messages
```

**Comment by AstroTibs** [comment]
Hopefully this will be of use?

https://mclo.gs/xZ1LcoP (PolyMC log)

[fml-client-latest.log](https://github.com/GTNewHorizons/Hodgepodge/files/10476991/fml-client-latest.log)

Mods used:
```
CodeChickenLib-1.7.10-1.1.5.5
CodeChickenCore-1.7.10-1.1.6
ForgeMultipart-1.7.10-1.2.0.347-universal
gtnhlib-1.7.10-0.0.6
gtnhmixins-2.1.2
hodgepodge-1.7.10-2.0.18
Mekanism-1.7.10-Community-Edition-1.7.10-9.10.23-Core
NotEnoughItems-1.7.10-2.3.19-GTNH
```

I loaded the game, signed into a world, accessed an Energized Smelter, and placed a stack of iron dust into it. The E.S. had energy and an empty output slot, so nothing should be preventing it from smelting.

**Comment by Glease** [comment]
maybe nbt insensitive itemstackmap returned a wildcard NBT tag on iteration.. need verification later.

**Comment by Glease** [comment]
this is technically a bug with mekanism. they are overly strict at recipe input checking. If they want to 100% replicate the vanilla furnace behavior, they need to disable NBT checking. we can attempt a fix here in hodgepodge, but if they don't change NBT behavior, their furnace won't work for every furnace recipe vanilla furnace can do. To verify my theory, you can try add forestry and binnie to the instance. Apiarist DNA sample will not be accepted by the mekanism furnace (without hodgepodge), but vanilla furnace will be able to process it into Blank Sequence.

**Comment by AstroTibs** [comment]
I reported it to M:CE
https://github.com/Thorfusion/Mekanism-Community-Edition/issues/86

**Comment by Glease** [comment]
After the linked PR in GTNHLib is merged, the mekanism furnace will go back to its old state: usable on most recipes but not working for items with NBT.

I think it cannot even handle a simple rename actually... like rename the ore with a naming tag in anvil.
