### ISSUE TITLE
IC2 night vision fix not working

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/Hodgepodge#20]
Modpack version: GTNH 2.1.0.0
Hodgepodge Version: hodgepodge-1.7.10-1.6.6
Spongemixins Version: SpongeMixins-1.3.1

What happened?
Activated night vision with IC2 armor still gives blindness debuff

Expected IC2 night vision fix to no longer give the blindness debuff when nightvision is activated and player is in bright light (either artificial or sunlight)

Tested with:
NanoHelmet (IC2)
QuantumHelmet (IC2)
Quantum Goggles of Revealing (Electro-Magic Tools)

Fix is enabled in the config (`B:fixIc2Nightvision=true`)

[fml-client-latest - Kopie.log](https://github.com/GTNewHorizons/Hodgepodge/files/6386547/fml-client-latest.-.Kopie.log)

**Comment by Storyboard-MC** [comment]
This issue is still there in DEV 2.1.0.6b 
![javaw_JjEZxBL4JB 1](https://user-images.githubusercontent.com/55212472/116345857-f880a900-a7b6-11eb-8c3f-bb4b9d252caa.png)
I am only using Forge for the server

**Comment by GTNH-Afx237v7** [comment]
Screenshot of the Quantum Suit Helmet that I tested with, still gives blindness

![2021-04-28_11 17 15](https://user-images.githubusercontent.com/64365566/116379724-973af300-a813-11eb-9a5a-2f9227df93a7.png)

**Comment by GTNH-Afx237v7** [comment]
So the update to 1.6.7 fixed it - works fine now with IC2 Nanosuit Helmet and Quantumsuit Helmet.

Also works with ElectroMagicTools Quantumsuit Goggles of Revealing:
![grafik](https://user-images.githubusercontent.com/64365566/116966856-59294d80-acb1-11eb-8a64-9e5bb8e1c473.png)
![grafik](https://user-images.githubusercontent.com/64365566/116966893-6f370e00-acb1-11eb-8f1c-bf801fc13b2c.png)

Also works with ElectroMagicTools Solar Goggles of Revealing:
![grafik](https://user-images.githubusercontent.com/64365566/116967298-44998500-acb2-11eb-9dd6-c794f790d11a.png)
![grafik](https://user-images.githubusercontent.com/64365566/116967324-53803780-acb2-11eb-988d-06051d20baf0.png)


However does not work with ElectroMagicTools Nanosuit Goggles of Revealing (still gives blindness effect):
![grafik](https://user-images.githubusercontent.com/64365566/116967074-d2c13b80-acb1-11eb-8b53-cc8358388314.png)
![grafik](https://user-images.githubusercontent.com/64365566/116967165-01d7ad00-acb2-11eb-8fba-4a795a3fddb1.png)
