### ISSUE TITLE
Add client/server side support

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/Hodgepodge#21]
```
[17:12:22] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/GuiGameOver (java.lang.ClassNotFoundException: The specified class 'net.minecraft.client.gui.GuiGameOver' was not found)
[17:12:22] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.GuiGameOver was not found mixins.hodgepodge.json:fixGuiGameOver.MixinGuiGameOver
```

**Comment by jss2a98aj** [comment]
I started checking sides by doing this recently, as the Forge function I had been using was completely unreliable:
		boolean clientSide = true;
		try {
			Class.forName("net.minecraft.client.gui.FontRenderer", false, config.getClass().getClassLoader());
		} catch (ClassNotFoundException e) {
			clientSide = false;
		}
The forName call shouldn't cause the class to be initialized because of the second parameter being false.

**Comment by draknyte1** [comment]
Why not use `FMLCommonHandler.instance().getEffectiveSide().isClient();/isServer()`?

It can be called after `[GradleStart]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin` happens and return valid resultts. (I don't believe you can even run code prior to this happening.

**Comment by mitchej123** [comment]
```java
    public boolean shouldLoad(List<TargetedMod> loadedMods) {
        return (
            (side == Side.BOTH
                    || (side == Side.SERVER && FMLLaunchHandler.side().isServer())
                    || (side == Side.CLIENT && FMLLaunchHandler.side().isClient())
            )
                && applyIf.get()
                && loadedMods.containsAll(targetedMods)
        );
    }
    ```

Forgot to close this, borrowed the above code and it seems to be working.
