### ISSUE TITLE
"Fix some items restore 0 hunger" for Hunger overhaul causes crash with some mods

### ISSUE THREAD

**Issue by kotmatross28729** [GTNewHorizons/Hodgepodge#214]
If `B:fixHungerOverhaulRestore0Hunger=true` , then if there are [serene seasons](https://github.com/DarkShadow44/SereneSeasons) or betterfps, the game will crash https://pastebin.com/Cs0atBrm.

**Comment by DarkShadow44** [comment]
It's a Nullpointer exception in SereneSeasons, I fixed that just now. Will release the changes soon, I'll post it to the other issue in the SereneSeasons repo.

**Comment by wlhlm** [comment]
Thanks for the heads up. Closing.
