### ISSUE TITLE
Hodgepodge break better fps

### ISSUE THREAD

**Issue by kotmatross28729** [GTNewHorizons/Hodgepodge#229]
If hodgepodge and better fps are installed, better fps seems to work, but the menu on F12 for changing algorithms doesn't open.
If you add HungerOverhaul and HarvestCraft, and also the "Fix some items restore 0 hunger" option is enabled (by default), the game will crash: https://pastebin.com/ugBbXaga

If "B:fixHungerOverhaulRestore0Hunger=false" in hodgepodge config or hodgepodge is missing, the game doesn't crash

**Comment by mitchej123** [comment]
It looks like the hodgepoge fix assumes the NH version of HarvestCraft, and crashes with the vanilla one.  Disabling the config seems reasonable.

**Comment by kotmatross28729** [comment]
It seems like no, this fix works with the vanilla version of HarvestCraft. The error occurs precisely in the presence of better fps (as it was with serene seasons). The error also occurs when using GTNH version of HarvestCraft, doesn't matter. The crash report mentions something about: `Class transformer null safety: found misbehaving transformers:` (line 90). The same thing happened with serene seasons. I don’t know exactly what this means, but 4 lines with `return null;` were enough to fix this with ss. By the way, in the crash report (90) it says `returned non-null result: 0` or something like that, I think it's related

**Comment by mitchej123** [comment]
oh yah, I remember some troubles with better fps from the past, was some weird asm interactions that I never got to the bottom of.
