### ISSUE TITLE
Hodgepodge crashes the game on startup. 

### ISSUE THREAD

**Issue by toErIpNid** [GTNewHorizons/Hodgepodge#263]
Title. Also notified FalseTweak's issue tracker of the same crash in case it's on their end. 

Log: https://hastebin.skyra.pw/fosufikeca.md

**Comment by mitchej123** [comment]
Hodgepodge is not compatible with false tweaks. Others have gotten them to work together by playing with the options in the past, but given their hostility it is not likely to be fixed.
