### ISSUE TITLE
preventPickupLoot is too aggressive

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/Hodgepodge#27]
The `preventPickupLoot` option prevents any `EntityLivingBase` from picking up items using using vanilla's built-in item pickup mechanism. This is a problem in my [fox backport](https://github.com/makamys/DMod) since it makes foxes (who extend `EntityAnimal`) unable to pick up dropped items.

According to the documentation, the intention is to only prevent *monsters* from picking up items, so I think a check should be added to only apply the override if the entity is an `EntityMob`. Or at the very least, `EntityAgeable`s should be whitelisted (the nearest common superclass of animals and villagers).

**Comment by mitchej123** [comment]
Didn't notice this issue until recently; I'll take a look into it.

**Comment by makamys** [comment]
The issue still happens. Was this closed by mistake, or should I take this as a "Won't Fix"?

**Comment by mitchej123** [comment]
I'd be open to a PR if someone wants to adjust it, but with the mods in GTNH it's working as intended.

**Comment by Minepolz320** [comment]
Yep!
