### ISSUE TITLE
2.3.23-pre causes crash.

### ISSUE THREAD

**Issue by MagmaBro123** [GTNewHorizons/Hodgepodge#271]
Title.

https://pastebin.com/saJwmCYB

No report is created, and all I'm seeing is a java.lang.ArrayIndexOutOfBoundsException error at the bottom.

**Comment by DrParadox7** [comment]
These logs can't help. Try isolating which config or mod creates this issue.

**Comment by MagmaBro123** [comment]
Future versions fixed this issue. Not sure why it took 3 months for a response.
