### ISSUE TITLE
cofhWorldTransformer disables MFR Deep Storage Unit

### ISSUE THREAD

**Issue by poodledeer** [GTNewHorizons/Hodgepodge#308]
With CoFHCore, Hodgepodge, and MineFactory Reloaded installed, MFR's "Deep Storage Unit" does not store items correctly, instead voiding them.

Disabling `cofhWorldTransformer` in Hodgepodge's config fixes this.

To reproduce:
1. Install a new [lwjgl3ify instance](https://github.com/GTNewHorizons/lwjgl3ify#non-gtnh-1710-instance-setup), with CoFHCore and MineFactory Reloaded and omitting hodgepodge.
2. On a new world, place and insert many stacks of the same item into a Deep Storage Unit from MFR. See the "Count" indicator increase.
3. Install Hodgepodge.
5. Start the game, join a world.
6. Place a new Deep Storage Unit and attempt to insert items into it. The "Count" indicator never increases, and stacks of items are voided if shift-clicked into the container. Other ways of interacting with the block will insert into its input and output GUI slots and refuse to interact if those are full.

Mods:
- `CoFHCore-[1.7.10]3.1.4-329.jar`
- `hodgepodge-2.4.9.jar`
- `MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar`

As the cofhWorldTransformer config setting disables a CoFHCore feature, this removal is likely beneficial to some target mod packs. However, as it is on by default and leaves no information when an attempt is made to access the tileentity cache, this removes functionality from mods which depend on the CofHcore.

**Comment by mitchej123** [comment]
We looked around for mods that accessed it and were unable to find any.  It's a giant memory leak as is.

Either way, if someone wants to blacklist it running for certain mods, like MFR, I'm not opposed.

**Comment by unilock** [comment]
@mitchej123 Would it be correct to simply replace all instances of `cofh_validate()` with Forge's own `validate()`?  
That's what I did in my fork of MFR ([link](https://github.com/skyboy/MineFactoryReloaded/compare/1.7.10...unilock:MineFactoryReloaded:1.7.10#diff-46f4c0c10db4029ba54b27e9accd70afc1557eaa8e0ef2403a0c79f931cf60c7)), but I'm not sure if that's the "right" way to do it.

**Comment by mitchej123** [comment]
Seems reasonable, and doable via ASM.  To be honest I hadn't looked into it at all...

**Comment by unilock** [comment]
Oh, I meant to ask whether that would be appropriate to do in a fork of a mod to fix the issue manually. But doing it automatically via ASM would be neat, too :p

**Comment by mitchej123** [comment]
I'm not entirely sure why it's relying on that anyway, and relying on a cache that never gets purged and just leaks tiles... seems fragile.  If it works in your fork that sounds great.
