### ISSUE TITLE
Random and common in-world crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [GTNewHorizons/Hodgepodge#318]
Title, see modlist in report.

[crash-2024-01-31_13.48.03-client.txt](https://github.com/GTNewHorizons/Hodgepodge/files/14117162/crash-2024-01-31_13.48.03-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/Hodgepodge/files/14117165/fml-client-latest.log)

**Comment by mitchej123** [comment]
Fixed with https://github.com/GTNewHorizons/Hodgepodge/pull/319 and in 2.4.19
