### ISSUE TITLE
Caught exception from ForgeMultipart

### ISSUE THREAD

**Issue by s0u7a** [GTNewHorizons/Hodgepodge#353]
https://mclo.gs/C3N7660
latest forgemultipart.

**Comment by s0u7a** [comment]
Does this require opening an issue in lwjgl3ify?

**Comment by eigenraven** [comment]
The issue is fixed in the gtnh fork for forgemultipart https://github.com/GTNewHorizons/ForgeMultipart/.

**Comment by s0u7a** [comment]
thx
