### ISSUE TITLE
Crash with FalseTweaks

### ISSUE THREAD

**Issue by xronin01** [GTNewHorizons/Hodgepodge#355]
[latest.log](https://github.com/GTNewHorizons/Hodgepodge/files/14921786/latest.log)

**Comment by xronin01** [comment]
https://github.com/FalsePattern/FalseTweaks

**Comment by mitchej123** [comment]
Falsetweaks is fairly invasive, touches a lot of the same code as Hodgepodge, and is not officially supported with Hodgepodge.   I'd suggest disabling the overlapping mixins.
