### ISSUE TITLE
Does not work on offline mode servers

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [GTNewHorizons/Hodgepodge#397]
Hello, my friend wants to join my server however I had to turn off offline mode. Hes getting this weird message
![image](https://github.com/user-attachments/assets/f3ba4e42-4036-42eb-aed4-f235d0d131e4)

**Comment by Caedis** [comment]
Have your friend logon to your server with their account while the server is in online mode, then you can disable online mode and they can join as long as the account name is the same.
