### ISSUE TITLE
2.5.39-pre crashes

### ISSUE THREAD

**Issue by Omgise** [GTNewHorizons/Hodgepodge#400]
[crash-2024-07-29_05.56.38-client.txt](https://github.com/user-attachments/files/16405335/crash-2024-07-29_05.56.38-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/16405338/fml-client-latest.log)
[latest.log](https://github.com/user-attachments/files/16405339/latest.log)

**Comment by MagmaBro123** [comment]
39 and 40 are having a LOT of mod compat issues.
