### ISSUE TITLE
Mac crash on load

### ISSUE THREAD

**Issue by KibaTheBarbarian** [GTNewHorizons/Hodgepodge#77]
So somebody was getting a unique crash on my Modpack and only they got it on load and they have a Mac device
and turning off
Removes duplicate Fermenter and Squeezer recipes and flower registration
B:deduplicateForestryCompatInBOP=false    

Allow 5 Fir Sapling planted together ('+' shape) to grow to a big fir tree
B:makeBigFirsPlantable=false
fixed it
the crash log
https://pastebin.com/jgmTUwZc
I think it's a uppercase and lowercase thing

**Comment by mitchej123** [comment]
Make sure to grab the BOP from curse.  Should be fixed in GTNH 2.2.0.0
